# Generated by Django 5.0.2 on 2024-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('binyan', models.CharField(blank=True, max_length=50, null=True)),
                ('word', models.CharField(max_length=50)),
                ('word_u', models.CharField(max_length=50)),
                ('word_a', models.CharField(max_length=50)),
                ('words1', models.CharField(max_length=50)),
                ('words', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Vocabulary',
                'verbose_name_plural': 'Vocabulary',
            },
        ),
    ]
