# Generated by Django 5.0.2 on 2024-06-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Root',
                'verbose_name_plural': 'Roots',
            },
        ),
    ]
