# Generated by Django 5.0.2 on 2024-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0003_alter_vocabulary_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binyan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binyan', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Binyan',
                'verbose_name_plural': 'Binyans',
            },
        ),
        migrations.AddField(
            model_name='root',
            name='binyans',
            field=models.ManyToManyField(blank=True, to='ivrit.binyan'),
        ),
    ]
