# Generated by Django 5.0.2 on 2024-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0005_alter_root_options_alter_vocabulary_binyan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='binyan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='root',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word_u',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='words1',
            field=models.CharField(max_length=255),
        ),
    ]
