# Generated by Django 5.0.2 on 2024-06-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0006_alter_vocabulary_binyan_alter_vocabulary_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisok6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roots', models.CharField(max_length=255)),
                ('words', models.CharField(max_length=255)),
                ('tables', models.IntegerField(default=0)),
                ('tables_2', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Spisok 6',
                'verbose_name_plural': 'Spisok 6',
            },
        ),
    ]
