# Generated by Django 5.0.2 on 2024-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0009_rcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisok1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roots', models.CharField(max_length=255)),
                ('words', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
                ('r', models.CharField(max_length=100)),
                ('links', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Spisok 1',
                'verbose_name_plural': ' Spisok 1',
                'ordering': ['links'],
            },
        ),
        migrations.AlterModelOptions(
            name='rcategory',
            options={'ordering': ['r'], 'verbose_name': 'R-Category', 'verbose_name_plural': 'R-Categories'},
        ),
        migrations.AlterModelOptions(
            name='spisok6',
            options={'ordering': ['tables', 'roots'], 'verbose_name': 'Spisok 6', 'verbose_name_plural': ' Spisok 6'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ['root'], 'verbose_name': 'Vocabulary', 'verbose_name_plural': ' Vocabulary'},
        ),
    ]
