# Generated by Django 5.0.2 on 2024-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0011_alter_spisok1_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok1',
            name='links',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
