# Generated by Django 5.0.2 on 2024-07-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0012_alter_spisok1_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binyan',
            options={'ordering': ['binyan'], 'verbose_name': 'Binyan', 'verbose_name_plural': 'Binyans'},
        ),
        migrations.AddField(
            model_name='root',
            name='number',
            field=models.IntegerField(default=100000),
        ),
    ]
