# Generated by Django 5.0.2 on 2024-07-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0013_alter_binyan_options_root_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='binyans',
        ),
        migrations.DeleteModel(
            name='Binyan',
        ),
    ]
