# Generated by Django 5.0.2 on 2024-07-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0014_remove_root_binyans_delete_binyan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binyan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binyan', models.CharField(max_length=50)),
                ('link', models.CharField(default='', max_length=100)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binyans', to='ivrit.root')),
            ],
            options={
                'verbose_name': 'Binyan',
                'verbose_name_plural': 'Binyans',
                'ordering': ['binyan'],
            },
        ),
    ]
