# Generated by Django 5.0.2 on 2024-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0016_alter_binyan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='root',
            name='group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='root',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
