# Generated by Django 5.0.2 on 2024-07-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0017_alter_root_group_alter_root_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='group',
        ),
        migrations.RemoveField(
            model_name='root',
            name='number',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('roots', models.ManyToManyField(blank=True, to='ivrit.root')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['group'],
            },
        ),
    ]
