# Generated by Django 5.0.2 on 2024-07-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0018_remove_root_group_remove_root_number_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='roots',
            field=models.ManyToManyField(blank=True, related_name='groups', to='ivrit.root'),
        ),
    ]
