# Generated by Django 5.0.2 on 2024-07-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0019_alter_group_roots'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
