# Generated by Django 5.0.2 on 2024-07-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0020_root_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='root',
            name='number',
            field=models.IntegerField(default=10000),
        ),
    ]
