# Generated by Django 5.0.2 on 2024-07-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0022_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='payment_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма платежа'),
        ),
    ]
