# Generated by Django 5.0.2 on 2024-07-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0023_setting_payment_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_en',
            field=models.TextField(blank=True, default='', verbose_name='Справка (EN)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_ru',
            field=models.TextField(blank=True, default='', verbose_name='Справка (RU)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_ua',
            field=models.TextField(blank=True, default='', verbose_name='Справка (UA)'),
        ),
    ]
