# Generated by Django 5.0.2 on 2024-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0024_setting_about_en_setting_about_ru_setting_about_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='words2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
