# Generated by Django 5.0.2 on 2024-07-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0026_kluch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='filter_for_app',
            field=models.BooleanField(default=False),
        ),
    ]
