# Generated by Django 5.0.2 on 2024-07-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0027_vocabulary_filter_for_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kluch',
            options={'ordering': ['value'], 'verbose_name': 'Ключ', 'verbose_name_plural': 'Ключи'},
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='words_clear',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
