# Generated by Django 5.0.2 on 2024-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0028_alter_kluch_options_vocabulary_words_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='app_about_en',
            field=models.TextField(blank=True, default='', verbose_name='Справка App (EN)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='app_about_il',
            field=models.TextField(blank=True, default='', verbose_name='Справка App (IL)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='app_about_ru',
            field=models.TextField(blank=True, default='', verbose_name='Справка App (RU)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='app_about_ua',
            field=models.TextField(blank=True, default='', verbose_name='Справка App (UA)'),
        ),
    ]
