# Generated by Django 5.0.2 on 2024-08-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0029_setting_app_about_en_setting_app_about_il_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='filter_for_app',
        ),
        migrations.AddField(
            model_name='kluch',
            name='value_en',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ (EN)'),
        ),
        migrations.AddField(
            model_name='kluch',
            name='value_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ (RU)'),
        ),
        migrations.AddField(
            model_name='kluch',
            name='value_ua',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ (UA)'),
        ),
    ]
