# Generated by Django 5.0.2 on 2024-08-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0030_remove_vocabulary_filter_for_app_kluch_value_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluch',
            name='root',
            field=models.CharField(default='', max_length=255, verbose_name='Корень'),
        ),
    ]
