# Generated by Django 5.0.2 on 2024-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrit', '0032_setting_app_verb_about_en_setting_app_verb_about_il_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='app_binyan_about_en',
            field=models.TextField(blank=True, default='', verbose_name='Справка App Binyan (EN)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='app_binyan_about_il',
            field=models.TextField(blank=True, default='', verbose_name='Справка App Binyan (IL)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='app_binyan_about_ru',
            field=models.TextField(blank=True, default='', verbose_name='Справка App Binyan (RU)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='app_binyan_about_ua',
            field=models.TextField(blank=True, default='', verbose_name='Справка App Binyan (UA)'),
        ),
    ]
