# Generated by Django 5.0.2 on 2024-11-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binyan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binyaninapp',
            options={'ordering': ['sort'], 'verbose_name': 'Биньян в приложении', 'verbose_name_plural': 'Биньяны в приложении'},
        ),
        migrations.AddField(
            model_name='binyaninapp',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
